### PR TITLE
Move repm to zerolog

### PR DESCRIPTION
**Pull request by aboodman**
Addresses rocicorp/replicache#45 in repm

### CODE REVIEW

**Comment by aboodman** [comment]
> Do you see any value in defining our own log.Debug/etc that delegates to zlog under the hood?

I considered that. The value would be that developers wouldn't accidentally use log levels we don't want to use. But the downside is that the interface to zerolog is huge, and we'd have to duplicate all of it. Didn't seem worth it.

**Comment by phritz** [comment]
> I considered that. The value would be that developers wouldn't accidentally use log levels we don't want to use. But the downside is that the interface to zerolog is huge, and we'd have to duplicate all of it. Didn't seem worth it.

Happy to not have it but I'm not sure why the size of the zerolog interface would matter? To be concrete what I was considering is:
 - have our rlog package define a logger like this:
```
package rlog

type Logger struct {...}

func (l *Logger) Debug(format string, v ...interface{}) {...}
func (l *Logger) Info(format string, v ...interface{}) {...}
func (l *Logger) Error(format string, v ...interface{}) {...}
```
- have client and diffserver depend on `rlog.Logger`, this is the thing we pass up and down our stacks
- the implementation of `rlog.Logger` uses zerolog under the hood

I guess logger would need to provide some configuration calls as well. Additional advantage is that it is easier to type log.Info and whatever, and we could switch out implementations.

I am not, however, advocating we necessarily do this. What we have now works fine.

**Comment by aboodman** [comment]
The zlog interface has all kinds of cool tricks though with
adding additional tags to log lines, generating stack traces, etc. The
current code I wrote makes use of that stuff up and down the stack. So we'd
want to duplicate that part of the interface too. I just couldn't think of
a way to do it that didn't involve copying/wrapping the entire zlog
interface, which seemed like a big maintenance burden, not to mention extra
code size for not great reason.

**Comment by phritz** [comment]
Makes sense 👍

**Pull request merged**
